//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestyJezyka
{
    using System;
    using System.Collections.Generic;
    
    public partial class MocZamowiona
    {
        public int Id { get; set; }
        public int idPrzylacze { get; set; }
        public byte Miesiac { get; set; }
        public byte Rok { get; set; }
        public float Ilosc { get; set; }
    
        public virtual Przylacze Przylacze { get; set; }
    }
}
