//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestyJezyka
{
    using System;
    using System.Collections.Generic;
    
    public partial class StawkaVAT
    {
        public StawkaVAT()
        {
            this.Cena = new HashSet<Cena>();
        }
    
        public int Id { get; set; }
        public string Kod { get; set; }
        public Nullable<float> Wartosc { get; set; }
    
        public virtual ICollection<Cena> Cena { get; set; }
    }
}
