//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cena
    {
        public int Id { get; set; }
        public int idSkladnikTaryfy { get; set; }
        public Nullable<System.DateTime> DataOd { get; set; }
        public Nullable<int> idStawkaVAT { get; set; }
        public Nullable<decimal> Cena1 { get; set; }
        public Nullable<decimal> CenaZima { get; set; }
    
        public virtual SkladnikTaryfy SkladnikTaryfy { get; set; }
        public virtual StawkaVAT StawkaVAT { get; set; }
    }
}
