//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OsrodekKosztow
    {
        public int Id { get; set; }
        public int idPrzylacze { get; set; }
        public string Nazwa { get; set; }
        public float ProcentKosztow { get; set; }
        public float UdzialZuzycia { get; set; }
        public int idRok { get; set; }
        public string KontoKosztuStale { get; set; }
        public string KontoKosztuZmienne { get; set; }
    
        public virtual Przylacze Przylacze { get; set; }
        public virtual Rok Rok { get; set; }
    }
}
